#!/usr/bin/env bash
# Lappy-side deployment for pi-stt-server (user units, GPU whisper).
# Run ON LAPPY as the owning user. Installs/updates the user-level
# socket-activated service that serves whisper large-v3-turbo on CUDA.
#
# Prerequisites: this checkout at ~/pi-stt-server with origin/main fetched,
# NVIDIA driver loaded, CUDA-capable GPU.
set -Eeuo pipefail

cd "$(dirname "$0")"
LAPPY_ENV=./lappy.env

echo "→ Creating/updating venv"
python3 -m venv venv
venv/bin/pip install --quiet --upgrade pip
venv/bin/pip install --quiet -r requirements.txt
venv/bin/pip check

echo "→ Resolving NVIDIA pip library directories for LD_LIBRARY_PATH"
libs="$(venv/bin/python - <<'PY'
import glob
dirs = sorted(glob.glob("venv/lib/python*/site-packages/nvidia/*/lib"))
print(":".join(dirs))
PY
)"
[[ -n "$libs" ]] || { echo "ERROR: no nvidia pip lib dirs found (is faster-whisper installed?)" >&2; exit 1; }
echo "  $libs"

echo "→ Writing $LAPPY_ENV (untracked)"
cat >"$LAPPY_ENV" <<EOF
# Generated by deploy-lappy.sh — LD_LIBRARY_PATH for CTranslate2 CUDA.
LD_LIBRARY_PATH=$libs
EOF
chmod 600 "$LAPPY_ENV"

echo "→ Testing engine import under the unit's library path"
LD_LIBRARY_PATH="$libs" venv/bin/python -c "
from faster_whisper import WhisperModel
import ctranslate2
n = ctranslate2.get_cuda_device_count()
print('ct2 cuda devices:', n)
if n < 1:
    raise SystemExit('no CUDA device visible')
"

echo "→ Running tests (fake engines)"
venv/bin/python -m pytest test/ -q

echo "→ Installing user units"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
mkdir -p "$UNIT_DIR"
install -m 0644 systemd/lappy/pi-stt-server.socket "$UNIT_DIR/pi-stt-server.socket"
install -m 0644 systemd/lappy/pi-stt-server.service "$UNIT_DIR/pi-stt-server.service"
systemctl --user daemon-reload
systemctl --user enable --now pi-stt-server.socket

echo "→ Waiting for socket activation smoke"
for _ in {1..40}; do
  if curl -fsS --max-time 3 http://127.0.0.1:8182/health >/tmp/pi-stt-lappy-health.json 2>/dev/null; then
    break
  fi
  sleep 0.5
done
python3 - <<'PY'
import json, sys
body = json.load(open("/tmp/pi-stt-lappy-health.json"))
if body.get("status") != "ok" or body.get("modelAvailable") is not True:
    raise SystemExit("health check failed")
engines = body.get("engines", {})
if set(engines) != {"whisper"}:
    raise SystemExit(f"unexpected engine set on Lappy: {list(engines)}")
if engines["whisper"].get("model") != "large-v3-turbo":
    raise SystemExit(f"unexpected whisper model: {engines['whisper']}")
print("health OK:", engines["whisper"])
PY

echo "✅ pi-stt-server (Lappy, GPU whisper) deployed — lazily activated on first /transcribe"
